### PR TITLE
SoapyUHDDevice: implemented DC offset and IQ Balance APIs

### PR DESCRIPTION
**Pull request by ncorgan**

### CODE REVIEW

**Comment by ncorgan** [comment]
With how recent the IQBalanceMode changes are, I haven't included it here, but it's trivial to implement, depending on how you want to deal with compatibility.

**Comment by ncorgan** [comment]
With https://github.com/pothosware/SoapySDR/commit/349296050fc2d0d40e86b7834e9273599bfa387f commited, I'll implement those functions here tonight or tomorrow. I don't have access to the USRP I used to test previous pull requests, so I'll need you to test it.

How do you want to deal with SoapySDR compatibility? Should I surround them with the new compatibility `#define`? In theory, I should be able to unconditionally compile the functions, since it's an API addition and not a breakage. Older versions won't have a SoapySDR function to call into it, but since SoapyUHDDevice doesn't declare functions with `override`, the compiler wouldn't complain about an older version's SoapySDR device class not having the function.

**Comment by guruofquality** [comment]
The ifdefs are useful for `UHDSoapyDevice.cpp` when you have to call into a SoapySDR::Device inside of bound uhd functions.

You dont really need them in `SoapyUHDDevice.cpp` unless you have override. I say just do the simple thing and skip override and ifdef here.

**Comment by ncorgan** [comment]
As I said this morning, I don't have access to hardware to test this, so you'll have to verify.

**Pull request merged**
